version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - DB_URL=${DB_URL}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_PREFIX=${SERVER_PREFIX}
      - JWT_TTL=${JWT_TTL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: usa
      POSTGRES_PASSWORD: usa
      POSTGRES_DB: usa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  postgres_data:
